distr.plot.xy(Bid, TripHassle, plot.type = "scatter", fitline = T, data = Bidding)
cor(Bidding$Bid, Bidding$TripHassle)
distr.summary.x(Bidding$Bid, stats = "dispersion")
distr.plot.x(Cramp, plot.type = "boxplot", data = Bidding)
distr.summary.x(Cramp, stats = "fivenumbers", data = Bidding)
62 - 1.5*(106.62-78.64)
distr.table.xy(WouldRepeat, freq.type = "row", Motive, freq = "perc", data = Bidding)
distr.summary.x(WouldRepeat, by1 = Motive, stats = "central", data = Bidding)
distr.plot.xy(Motive,
              WouldRepeat, plot.type = "bars", data = Bidding)
distr.summary.x(Bid, by1 = Type, stats = "disp", data = Bidding)
(10.58)/sqrt(302)
mids <- c(7.5,11,16,27.5,40,52.5)
counts <- c(50,75,125,100,100,50)
mids1 <- rep(mids,counts)
distr.summary.x(mids1, stats = "fivenumbers")
distr.plot.x(mids1, plot.type = "boxplot")
